### ISSUE TITLE
adding extra launch parameter to EWBF miner causes miner to shutdown

### ISSUE THREAD

**Issue by mfmj** [gacopl/NiceHashMiner#10]
I tried to add an extra launch paramenter --pec to EWBF miner however it causes the miner to shutdown.

From the logs looks like space was added before the launch parameter, where it should be after the parameter:

`[2017-06-21 22:20:29] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "--pec" for device UUID GPU-68b8b056-4256-1ed8-b7d3-f8c1c1c58297`
`[2017-06-21 22:20:29] [INFO] [ExtraLaunchParametersParser] Final extra launch params parse " --pec"`
`[2017-06-21 22:20:29] [INFO] [ExtraLaunchParametersParser] DisableAMDTempControl is TRUE, temp control parameters will be ignored`
`[2017-06-21 22:20:29] [INFO] [ewbf-MINER_ID(4)-DEVICE_IDs(0)] Starting miner [pid(9156)|bin(bin_3rdparty\ewbf\miner.exe)]  --cuda_devices 0   --pec--server equihash.hk.nicehash.com --user 19NEBGbSghtykey76Ged7WKD5qoqj3enPy.htpc --pass x --port 3357 --api 0.0.0.0:4000`
`[2017-06-21 22:20:29] [INFO] [ewbf-MINER_ID(4)-DEVICE_IDs(0)] [pid(9156)|bin(bin_3rdparty\ewbf\miner.exe)] Starting cooldown checker`
`[2017-06-21 22:20:29] [INFO] [ewbf-MINER_ID(4)-DEVICE_IDs(0)] [pid(9156)|bin(bin_3rdparty\ewbf\miner.exe)] Miner_Exited Will restart in 5000 ms`

thanks for your work. really appreciate it

**Comment by gacopl** [comment]
stupid mistake, thanks for this catch i fixed it and updated release, please redownload :)

**Comment by ChriscomIT** [comment]
Thanks, I really appreciate your work too! I will tip a small amount next week. Thanks again!

**Comment by gacopl** [comment]
Thanks, tips are welcome so far more than 700 unique users and no tip at all :)

**Comment by ChriscomIT** [comment]
Sure you did good work! Ok is 700 the actual download numbers? Not bad! Yeah, I will tip with my next BTC payout.

**Comment by macber2** [comment]
@gacopl 
whats your take about nicehash banning accounts using mods

**Comment by ChriscomIT** [comment]
Nicehash is banning members/victims of botnets, not mods afaik. As well you can check the code for any suspicious bits as its open sourced and that's why as well meant to be forked IMO.

**Comment by gacopl** [comment]
Its not this kind of mod they are banning, besides as far as i know they encourage to fork and develop, they just lazy in including those mods into their master.

**Comment by mfmj** [comment]
thanks @gacopl issue is solved :) 
keep up the great work!

**Comment by ChriscomIT** [comment]
@gacopl How do you count the unique users? From download counter or did you implement a counter in your mod (which I cant see from the code)?

**Comment by gacopl** [comment]
from github stats

**Comment by ChriscomIT** [comment]
Thanks for the confirmation. Its what I thought! Again great work buddy! Tip is incoming the following week.
