### ISSUE TITLE
gtx 10XX p0 state

### ISSUE THREAD

**Issue by 008** [gacopl/NiceHashMiner#12]
Hi,
i know you have gtx1080, do you have P0 state ?

cmd
cd C:\Program Files\NVIDIA Corporation\NVSMI
nvidia-smi -q -d PERFORMANCE

i have only P2 state

the problem maybe in drivers?
this one makes N/A in the clocks "nvidia-smi -q -d SUPPORTED_CLOCKS"

(nvidiasetp0state.exe with admin rights dosnt helps)

**Comment by gacopl** [comment]
Unfortunately Pascals do not support changing pstate at least I could not
find way to do so

25.06.2017 22:13 "008" <notifications@github.com> napisał(a):
