### ISSUE TITLE
GUI corruption issue

### ISSUE THREAD

**Issue by ChriscomIT** [gacopl/NiceHashMiner#14]
I have an issue with the GUI. It gets corrupt after some time of using the app (around 2 or 3 hours but sometimes earlier) as can be seen in the screenshot below.

<img width="465" alt="nicehash gacomod gui corruption" src="https://user-images.githubusercontent.com/2799553/27664160-44baf654-5c66-11e7-87b5-0582c0d72ba5.PNG">

For reference the proper looking GUI below.

<img width="519" alt="nicehash gacomod gui" src="https://user-images.githubusercontent.com/2799553/27664268-ebdd01a2-5c66-11e7-8c1a-59e736e4076c.PNG">

**Comment by kpereira** [comment]
Yes I get the same issue. I don't know what triggers it. Sometimes it can be immediate, other times may not happen at all. Timing is random or tied to an event that I am unaware of.

**Comment by gacopl** [comment]
thanks same happens to me i will work on it over the weekend

**Comment by gacopl** [comment]
seems i fixed it i'll let it run for the rest of the day and release

**Comment by ChriscomIT** [comment]
Nice! GJ!

**Comment by gacopl** [comment]
fix released :)

**Comment by ChriscomIT** [comment]
Nice, thank you very much!!!!

**Comment by WieldSoftwareDevelopement** [comment]
Hi, Is the only way to get this fix to build the project yourself?

EDIT: I found the update in the released zip. Thanks!
[1.7.5.13-gaco-mod](https://github.com/gacopl/NiceHashMiner/releases/tag/1.7.5.13-gaco-mod)
