### ISSUE TITLE
Old version of EWBF CUDA Zcash miner used

### ISSUE THREAD

**Issue by kpereira** [gacopl/NiceHashMiner#2]
Old version of EWBF CUDA Zcash miner used

0.3.4b is the latest version available. Is there a reason it was not used?

**Comment by ChriscomIT** [comment]
Yeah, same question here. I just think @gacopl missed the release of new EWBF. For me, the new version 0.3.4b works great so I can't see why there should be any specific reason to not use it.

**Comment by kpereira** [comment]
I've been using 0.3.4b with this without problems so far.

**Comment by ChriscomIT** [comment]
@kpereira Ok sound good. For the GTANAdam fork, I just copied over the relevant miner files. So my guess was it will do the trick here as well with this fork. Thanks for the confirmation, as I not yet tried this fork.

**Comment by gacopl** [comment]
oh sorry i missed it i will update the bins thanks :)

**Comment by gacopl** [comment]
release updated
