### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by 008** [gacopl/NiceHashMiner#4]
just start it and hit Cancel in "would you like do bench now?"

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NullReferenceException: В экземпляре объекта не задана ссылка на объект.
   в NiceHashMiner.Form_Main.StopMining()
   в NiceHashMiner.Form_Main.StartupTimer_Tick(Object sender, EventArgs e)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
NiceHashMiner
    Версия сборки: 1.7.5.13
    Версия Win32: 1.7.5.13
    CodeBase: file:///C:/NiceHashMiner-mod/NiceHashMiner.exe
----------------------------------------
System
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8793 (WinRelRS2.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Версия сборки: 7.0.0.0
    Версия Win32: 7.0.1.18622
    CodeBase: file:///C:/NiceHashMiner-mod/Newtonsoft.Json.DLL
----------------------------------------
System.Management
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8794 (WinRelRS2.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Management/2.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Xml
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
log4net
    Версия сборки: 1.2.15.0
    Версия Win32: 1.2.15.0
    CodeBase: file:///C:/NiceHashMiner-mod/log4net.DLL
----------------------------------------
System.Configuration
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
MessageBoxManager
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/NiceHashMiner-mod/MessageBoxManager.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
MiniHttpd
    Версия сборки: 1.2.0.32072
    Версия Win32: 1.2.0.32072
    CodeBase: file:///C:/NiceHashMiner-mod/MiniHttpd.DLL
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by gacopl** [comment]
sorry cannot reproduce please make sure it is not because of the missing libs problems you had
