### ISSUE TITLE
Hello and thanks

### ISSUE THREAD

**Issue by imrecsoka** [gacopl/NiceHashMiner#7]
Hi, is this a bitcoin address so i can donate.
19EzHxJ5MD6sCD5Bwp1Z7n4rPboGrvoWnL
I trust there is no funny stuff going on underneath your fork ?

**Comment by gacopl** [comment]
yes and yes there is no funny stuff i spent couple days on putting this together, i just want to people start using it (this is my way to give back to open source community) to give me satisfaction and maybe some donations cause it really makes a difference, there is source available you can read it and even build it yourself. 
No funny stuff except i changed btc address for demo run, but lets be honest nobody runs it in demo mode for a second :)
