### ISSUE TITLE
GTX970 slow with ETH

### ISSUE THREAD

**Issue by HyperCriSiS** [gacopl/NiceHashMiner#8]
Hi,

dual mining works but with every Nicehash version I tried, I only get 3.5MH/s with ETH.
I could not find any solution.
Can you help?

Thanks and regards,
Hyper

**Comment by Arcandel** [comment]
i had that issue once on my 7x 1070 rig and was when i was playing with drivers....  clean driver install helped in my case.

**Comment by 008** [comment]
970 not for ETH

**Comment by gacopl** [comment]
Hi never had 970 so cannot tell, why you care about eth, the point of using nicehash is for it to mine you best coin, single ETH is usually inefficient in all nvidia cards i've seen, dual is best for 1070s and less and equihash is best for 1080 and 1080ti, but it all depepnds on demand sometimes other algos are more profitable, set it up properly and nhm will make sure you will earn best you can with your card.

**Comment by ChriscomIT** [comment]
ETH is pretty slow and inefficient on GTX900 series card like the others say. With my GTX980 I just get somewhat slightly higher mining speed as you. Just set up NHM properly and u will get the most out of it! Preferably mine Equihash as its best for NVIDIA cards.
